# Generated by Django 3.1.7 on 2021-03-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
