# Generated by Django 3.1.7 on 2021-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('start_date_of_employment', models.DateTimeField(auto_now=True)),
                ('route', models.CharField(max_length=400)),
            ],
        ),
    ]
